apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: java-springboot-ajkammve
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/java-springboot-ajkammve:0a01be10f909bda1ba1dddea93c81a5c955d90eb@sha256:19c114ad59082795f8a66eff630f740ec3a44683e030794bd27e99738d3c7453
          name: container-image
